// Key aliases

#define XXXXXX	  KEY_ERROR_UNDEFINED

#define STD_01		KEY_ESC
#define STD_02		KEY_F1
#define STD_03		KEY_F2
#define STD_04		KEY_F3
#define STD_05		KEY_F4
#define STD_06		KEY_F5
#define STD_07		KEY_F6
#define STD_08		KEY_F7
#define STD_09		KEY_F8
#define STD_10		KEY_F9
#define STD_11		KEY_F10
#define STD_12		KEY_F11
#define STD_13		KEY_F12
#define STD_14		KEY_INSERT
#define STD_15		KEY_DELETE
#define STD_16		KEY_ES_AO
#define STD_17		KEY_1
#define STD_18		KEY_2
#define STD_19		KEY_3
#define STD_20		KEY_4
#define STD_21		KEY_5
#define STD_22		KEY_6
#define STD_23		KEY_7
#define STD_24		KEY_8
#define STD_25		KEY_9
#define STD_26		KEY_0
#define STD_27		KEY_ES_QUOTE
#define STD_28		KEY_ES_INVMARKS
#define STD_29		KEY_BACKSPACE
#define STD_30		KEY_NUM_LOCK
#define STD_31		KEYPAD_DIVIDE
#define STD_32		KEYPAD_MULTIPLY
#define STD_33		KEYPAD_SUBTRACT
#define STD_34		KEY_TAB
#define STD_35		KEY_Q
#define STD_36		KEY_W
#define STD_37		KEY_E
#define STD_38		KEY_R
#define STD_39		KEY_T
#define STD_40		KEY_Y
#define STD_41		KEY_U
#define STD_42		KEY_I
#define STD_43		KEY_O
#define STD_44		KEY_P
#define STD_45		KEY_ES_CIRCUMFLEX
#define STD_46		KEY_ES_PLUS
#define STD_47		KEY_ENTER
#define STD_48		KEYPAD_7
#define STD_49		KEYPAD_8
#define STD_50		KEYPAD_9
#define STD_51		KEYPAD_ADD
#define STD_52		KEY_CAPS_LOCK
#define STD_53		KEY_A
#define STD_54		KEY_S
#define STD_55		KEY_D
#define STD_56		KEY_F
#define STD_57		KEY_G
#define STD_58		KEY_H
#define STD_59		KEY_J
#define STD_60		KEY_K
#define STD_61		KEY_L
#define STD_62		KEY_ES_NTILDE
#define STD_63		KEY_ES_UMLAUT
#define STD_64		KEY_ES_CEDILLA
#define STD_65		KEYPAD_4
#define STD_66		KEYPAD_5
#define STD_67		KEYPAD_6
#define STD_68		KEY_LEFT_SHIFT
#define STD_69		KEY_Z
#define STD_70		KEY_X
#define STD_71		KEY_C
#define STD_72		KEY_V
#define STD_73		KEY_B
#define STD_74		KEY_N
#define STD_75		KEY_M
#define STD_76		KEY_COMMA
#define STD_77		KEY_PERIOD
#define STD_78		KEY_ES_MINUS
#define STD_79		KEY_ES_LT_GT
#define STD_80		KEY_RIGHT_SHIFT
#define STD_81		KEY_UP
#define STD_82		KEYPAD_1
#define STD_83		KEYPAD_2
#define STD_84		KEYPAD_3
#define STD_85		KEYPAD_ENTER
#define STD_86		KEY_LEFT_CTRL
#define STD_87		KEY_LEFT_WINDOWS
#define STD_88		KEY_LEFT_ALT
#define STD_89		KEY_SPACE
#define STD_90		KEY_RIGHT_ALT
#define STD_91		KEY_F13
#define STD_92		KEY_RIGHT_CTRL
#define STD_93		KEY_LEFT
#define STD_94		KEY_DOWN
#define STD_95		KEY_RIGHT
#define STD_96		KEYPAD_0
#define STD_97		KEYPAD_DOT
